image: node:18

stages:
  - build

build:
  stage: build
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules/
  script:
    - yarn
    #set up .npmrc :clown:
    - echo "@kosygin-rsu:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    #build
    - CI=false yarn clean-build
    - yarn publish --verbose
    - echo "-- build completed succesfully"
  only:
    - master
    - develop
